[versions]
kotlin = "2.2.10"
shadow = "9.1.0"
minecraft = "1.21.8-R0.1-SNAPSHOT"
userdev = "2.0.0-beta.18"
pluginyml = "0.8.0"
runtask = "2.3.1"

configurate = "4.2.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }
pluginyml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginyml" }
runtask = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }

[libraries]
configurate = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }